# Generated by Django 5.2 on 2025-05-31 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Credit/Debit Card'), ('GCASH', 'GCash'), ('MAYA', 'Maya'), ('BANK', 'Bank Transfer')], max_length=20),
        ),
    ]
