# Generated by Django 5.1.5 on 2025-05-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
