# Generated by Django 5.2 on 2025-05-31 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_payment_payment_method'),
        ('patients', '0010_remove_ultrasoundexam_image_ultrasoundimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='service',
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.bill')),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill_item', to='patients.ultrasoundexam')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.servicetype')),
            ],
        ),
    ]
