# Generated by Django 5.1.5 on 2025-06-02 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_add_timestamps_to_servicetype'),
        ('billing', '0003_remove_bill_exam_remove_bill_service_billitem'),
    ]

    operations = [
    ]
