# Generated by Django 5.1.5 on 2025-08-23 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_bill_bill_date_alter_bill_bill_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='due_date',
        ),
    ]
