# Generated by Django 5.1.5 on 2025-08-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_remove_due_date_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='change',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Change to be given to patient', max_digits=10),
        ),
    ]
