# Generated by Django 5.1.5 on 2025-08-23 13:45

from django.db import migrations


def update_payment_methods(apps, schema_editor):
    Payment = apps.get_model('billing', 'Payment')
    
    # Update old payment methods to valid ones
    Payment.objects.filter(payment_method='CARD').update(payment_method='CASH')
    Payment.objects.filter(payment_method='MAYA').update(payment_method='GCASH')


def reverse_update_payment_methods(apps, schema_editor):
    Payment = apps.get_model('billing', 'Payment')
    
    # Reverse the changes (though this might not be accurate)
    Payment.objects.filter(payment_method='CASH').update(payment_method='CARD')
    Payment.objects.filter(payment_method='GCASH').update(payment_method='MAYA')


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_add_change_field_to_payment'),
    ]

    operations = [
        migrations.RunPython(update_payment_methods, reverse_update_payment_methods),
    ]
