# Generated by Django 5.1.5 on 2025-09-01 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_expense_alter_bill_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
