# Generated by Django 5.1.5 on 2025-11-12 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_delete_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/'),
        ),
    ]
