# Generated by Django 5.1.5 on 2025-12-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_servicetype_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('UTILITIES', 'Utilities'), ('RENT', 'Rent'), ('SALARY', 'Salary'), ('EQUIPMENT', 'Equipment'), ('SUPPLIES', 'Supplies'), ('MAINTENANCE', 'Maintenance'), ('MARKETING', 'Marketing'), ('INSURANCE', 'Insurance'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
