# Generated by Django 5.1.5 on 2025-05-31 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('patient_type', models.CharField(choices=[('REGULAR', 'Regular'), ('SENIOR', 'Senior Citizen'), ('PWD', 'Person with Disability')], default='REGULAR', max_length=10)),
                ('id_number', models.CharField(blank=True, help_text='Senior Citizen/PWD ID number', max_length=50, null=True)),
                ('region', models.CharField(max_length=100, verbose_name='Region')),
                ('province', models.CharField(max_length=100, verbose_name='Province')),
                ('city', models.CharField(max_length=100, verbose_name='City/Municipality')),
                ('barangay', models.CharField(max_length=100, verbose_name='Barangay')),
                ('street_address', models.TextField(help_text='House/Building Number, Street Name, etc.')),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UltrasoundExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referring_physician', models.CharField(max_length=100)),
                ('clinical_diagnosis', models.TextField()),
                ('medical_history', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='ultrasound_images/')),
                ('annotations', models.TextField(blank=True, null=True)),
                ('procedure_type', models.CharField(choices=[('ABD', 'Abdominal'), ('PEL', 'Pelvic'), ('OBS', 'Obstetric'), ('TVS', 'Transvaginal'), ('BRE', 'Breast'), ('THY', 'Thyroid'), ('SCR', 'Scrotal'), ('DOP', 'Doppler'), ('OTH', 'Other')], max_length=3)),
                ('doppler_site', models.CharField(blank=True, max_length=100, null=True)),
                ('other_procedure', models.CharField(blank=True, max_length=100, null=True)),
                ('exam_date', models.DateField()),
                ('exam_time', models.TimeField()),
                ('technologist', models.CharField(max_length=100)),
                ('radiologist', models.CharField(max_length=100)),
                ('findings', models.TextField()),
                ('impression', models.TextField()),
                ('recommendations', models.CharField(choices=[('FI', 'Further imaging'), ('FU', 'Follow-up ultrasound'), ('RS', 'Referral to specialist'), ('BI', 'Biopsy/FNA advised'), ('NF', 'No further workup needed')], max_length=2)),
                ('followup_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('specialist_referral', models.CharField(blank=True, max_length=100, null=True)),
                ('technologist_notes', models.TextField(blank=True, null=True)),
                ('technologist_signature', models.CharField(max_length=100)),
                ('radiologist_signature', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ultrasound_exams', to='patients.patient')),
            ],
            options={
                'ordering': ['-exam_date', '-exam_time'],
            },
        ),
    ]
