# Generated by Django 5.1.5 on 2025-05-31 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
    ]
