# Generated by Django 5.1.5 on 2025-05-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_options_remove_patient_hospital_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultrasoundexam',
            name='annotations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ultrasoundexam',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ultrasound_images/'),
        ),
    ]
