# Generated by Django 5.1.5 on 2025-05-31 08:43

from django.db import migrations

def split_name(apps, schema_editor):
    Patient = apps.get_model('patients', 'Patient')
    for patient in Patient.objects.all():
        if patient.name:
            name_parts = patient.name.split(' ', 1)
            patient.first_name = name_parts[0]
            patient.last_name = name_parts[1] if len(name_parts) > 1 else ''
            patient.save()

def combine_name(apps, schema_editor):
    Patient = apps.get_model('patients', 'Patient')
    for patient in Patient.objects.all():
        patient.name = f"{patient.first_name} {patient.last_name}".strip()
        patient.save()

class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_first_name_patient_last_name_and_more'),
    ]

    operations = [
        migrations.RunPython(split_name, combine_name),
    ]
