# Generated by Django 5.1.5 on 2025-05-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patient_address_patient_barangay_patient_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='barangay',
            field=models.CharField(default='none', max_length=100, verbose_name='Barangay'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=models.CharField(default='none', max_length=100, verbose_name='City/Municipality'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='province',
            field=models.CharField(default='none', max_length=100, verbose_name='Province'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='region',
            field=models.CharField(default='none', max_length=100, verbose_name='Region'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='street_address',
            field=models.TextField(default='none', help_text='House/Building Number, Street Name, etc.'),
            preserve_default=False,
        ),
    ]
