# Generated by Django 5.1.5 on 2025-05-29 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_ultrasoundexam_annotations_ultrasoundexam_image'),
        ('patients', '0004_alter_patient_barangay_alter_patient_city_and_more'),
    ]

    operations = [
    ]
