# Generated by Django 5.1.5 on 2025-05-31 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_update_name_fields'),
        ('patients', 'update_procedure_type'),
    ]

    operations = [
    ]
