# Generated by Django 5.2 on 2025-05-31 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_merge_0006_update_name_fields_update_procedure_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_status',
            field=models.CharField(choices=[('IN', 'Inpatient'), ('OUT', 'Outpatient')], default='OUT', max_length=3),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='', max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='', max_length=50, verbose_name='Last Name'),
        ),
    ]
