# Generated by Django 5.2 on 2025-05-31 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_patient_patient_status_alter_patient_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('W', 'Widowed'), ('D', 'Divorced')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='ultrasoundexam',
            name='amniotic_fluid',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ultrasoundexam',
            name='edd',
            field=models.DateField(blank=True, null=True, verbose_name='Estimated Date of Delivery'),
        ),
        migrations.AddField(
            model_name='ultrasoundexam',
            name='efw',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estimated Fetal Weight'),
        ),
        migrations.AddField(
            model_name='ultrasoundexam',
            name='fetal_heart_rate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ultrasoundexam',
            name='fetal_sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Undetermined')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='ultrasoundexam',
            name='or_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ultrasoundexam',
            name='placenta_grade',
            field=models.CharField(blank=True, choices=[('0', 'Grade 0'), ('1', 'Grade I'), ('2', 'Grade II'), ('3', 'Grade III')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='ultrasoundexam',
            name='placenta_location',
            field=models.CharField(blank=True, choices=[('ANT', 'Anterior'), ('POS', 'Posterior'), ('FUN', 'Fundal'), ('LAT', 'Lateral')], max_length=3, null=True),
        ),
    ]
