# Generated by Django 5.1.5 on 2025-05-31 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_patient_marital_status_ultrasoundexam_amniotic_fluid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ultrasoundexam',
            name='image',
        ),
        migrations.CreateModel(
            name='UltrasoundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ultrasound_images/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='patients.ultrasoundexam')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
