# Generated by Django 5.2 on 2025-05-31 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_remove_ultrasoundexam_image_ultrasoundimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultrasoundimage',
            name='annotations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
