# Generated by Django 5.2 on 2025-05-31 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_ultrasoundimage_annotations'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbdominalUltrasoundMeasurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liver_length', models.DecimalField(blank=True, decimal_places=2, help_text='Length in cm', max_digits=5, null=True)),
                ('liver_width', models.DecimalField(blank=True, decimal_places=2, help_text='Width in cm', max_digits=5, null=True)),
                ('liver_height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True)),
                ('liver_location', models.CharField(blank=True, max_length=100, null=True)),
                ('gallbladder_length', models.DecimalField(blank=True, decimal_places=2, help_text='Length in cm', max_digits=5, null=True)),
                ('gallbladder_width', models.DecimalField(blank=True, decimal_places=2, help_text='Width in cm', max_digits=5, null=True)),
                ('gallbladder_location', models.CharField(blank=True, max_length=100, null=True)),
                ('spleen_length', models.DecimalField(blank=True, decimal_places=2, help_text='Length in cm', max_digits=5, null=True)),
                ('spleen_width', models.DecimalField(blank=True, decimal_places=2, help_text='Width in cm', max_digits=5, null=True)),
                ('right_kidney_length', models.DecimalField(blank=True, decimal_places=2, help_text='Length in cm', max_digits=5, null=True)),
                ('right_kidney_width', models.DecimalField(blank=True, decimal_places=2, help_text='Width in cm', max_digits=5, null=True)),
                ('right_kidney_height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True)),
                ('left_kidney_length', models.DecimalField(blank=True, decimal_places=2, help_text='Length in cm', max_digits=5, null=True)),
                ('left_kidney_width', models.DecimalField(blank=True, decimal_places=2, help_text='Width in cm', max_digits=5, null=True)),
                ('left_kidney_height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ultrasound_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abdominal_measurements', to='patients.ultrasoundimage')),
            ],
            options={
                'verbose_name': 'Abdominal Ultrasound Measurement',
                'verbose_name_plural': 'Abdominal Ultrasound Measurements',
            },
        ),
        migrations.CreateModel(
            name='BreastUltrasoundMeasurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breast_side', models.CharField(choices=[('L', 'Left'), ('R', 'Right')], max_length=1)),
                ('mass_length', models.DecimalField(blank=True, decimal_places=2, help_text='Length in cm', max_digits=5, null=True)),
                ('mass_width', models.DecimalField(blank=True, decimal_places=2, help_text='Width in cm', max_digits=5, null=True)),
                ('mass_height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True)),
                ('mass_location', models.CharField(blank=True, help_text='Clock position and distance from nipple', max_length=100, null=True)),
                ('distance_from_nipple', models.DecimalField(blank=True, decimal_places=2, help_text='Distance in cm', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ultrasound_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breast_measurements', to='patients.ultrasoundimage')),
            ],
            options={
                'verbose_name': 'Breast Ultrasound Measurement',
                'verbose_name_plural': 'Breast Ultrasound Measurements',
            },
        ),
        migrations.CreateModel(
            name='PelvicUltrasoundMeasurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uterus_length', models.DecimalField(blank=True, decimal_places=2, help_text='Length in cm', max_digits=5, null=True)),
                ('uterus_width', models.DecimalField(blank=True, decimal_places=2, help_text='Width in cm', max_digits=5, null=True)),
                ('uterus_height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True)),
                ('endometrial_thickness', models.DecimalField(blank=True, decimal_places=2, help_text='Thickness in mm', max_digits=5, null=True)),
                ('right_ovary_length', models.DecimalField(blank=True, decimal_places=2, help_text='Length in cm', max_digits=5, null=True)),
                ('right_ovary_width', models.DecimalField(blank=True, decimal_places=2, help_text='Width in cm', max_digits=5, null=True)),
                ('right_ovary_height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True)),
                ('left_ovary_length', models.DecimalField(blank=True, decimal_places=2, help_text='Length in cm', max_digits=5, null=True)),
                ('left_ovary_width', models.DecimalField(blank=True, decimal_places=2, help_text='Width in cm', max_digits=5, null=True)),
                ('left_ovary_height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True)),
                ('right_ovary_location', models.CharField(blank=True, max_length=100, null=True)),
                ('left_ovary_location', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ultrasound_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pelvic_measurements', to='patients.ultrasoundimage')),
            ],
            options={
                'verbose_name': 'Pelvic Ultrasound Measurement',
                'verbose_name_plural': 'Pelvic Ultrasound Measurements',
            },
        ),
        migrations.CreateModel(
            name='ThyroidUltrasoundMeasurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_lobe_length', models.DecimalField(blank=True, decimal_places=2, help_text='Length in cm', max_digits=5, null=True)),
                ('right_lobe_width', models.DecimalField(blank=True, decimal_places=2, help_text='Width in cm', max_digits=5, null=True)),
                ('right_lobe_height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True)),
                ('left_lobe_length', models.DecimalField(blank=True, decimal_places=2, help_text='Length in cm', max_digits=5, null=True)),
                ('left_lobe_width', models.DecimalField(blank=True, decimal_places=2, help_text='Width in cm', max_digits=5, null=True)),
                ('left_lobe_height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True)),
                ('isthmus_thickness', models.DecimalField(blank=True, decimal_places=2, help_text='Thickness in mm', max_digits=5, null=True)),
                ('nodule_length', models.DecimalField(blank=True, decimal_places=2, help_text='Length in mm', max_digits=5, null=True)),
                ('nodule_width', models.DecimalField(blank=True, decimal_places=2, help_text='Width in mm', max_digits=5, null=True)),
                ('nodule_height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in mm', max_digits=5, null=True)),
                ('nodule_location', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ultrasound_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thyroid_measurements', to='patients.ultrasoundimage')),
            ],
            options={
                'verbose_name': 'Thyroid Ultrasound Measurement',
                'verbose_name_plural': 'Thyroid Ultrasound Measurements',
            },
        ),
    ]
