# Generated by Django 5.1.5 on 2025-06-01 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_familygroup_patient_family_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abdominalultrasoundmeasurements',
            name='gallbladder_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='abdominalultrasoundmeasurements',
            name='gallbladder_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='abdominalultrasoundmeasurements',
            name='left_kidney_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='abdominalultrasoundmeasurements',
            name='left_kidney_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='abdominalultrasoundmeasurements',
            name='left_kidney_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='abdominalultrasoundmeasurements',
            name='liver_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='abdominalultrasoundmeasurements',
            name='liver_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='abdominalultrasoundmeasurements',
            name='liver_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='abdominalultrasoundmeasurements',
            name='right_kidney_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='abdominalultrasoundmeasurements',
            name='right_kidney_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='abdominalultrasoundmeasurements',
            name='right_kidney_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='abdominalultrasoundmeasurements',
            name='spleen_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='abdominalultrasoundmeasurements',
            name='spleen_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='abdominalultrasoundmeasurements',
            name='ultrasound_image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.ultrasoundimage'),
        ),
        migrations.AlterField(
            model_name='breastultrasoundmeasurements',
            name='breast_side',
            field=models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='breastultrasoundmeasurements',
            name='distance_from_nipple',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='breastultrasoundmeasurements',
            name='mass_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='breastultrasoundmeasurements',
            name='mass_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='breastultrasoundmeasurements',
            name='mass_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='breastultrasoundmeasurements',
            name='mass_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='breastultrasoundmeasurements',
            name='ultrasound_image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.ultrasoundimage'),
        ),
        migrations.AlterField(
            model_name='pelvicultrasoundmeasurements',
            name='endometrial_thickness',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pelvicultrasoundmeasurements',
            name='left_ovary_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pelvicultrasoundmeasurements',
            name='left_ovary_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pelvicultrasoundmeasurements',
            name='left_ovary_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pelvicultrasoundmeasurements',
            name='right_ovary_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pelvicultrasoundmeasurements',
            name='right_ovary_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pelvicultrasoundmeasurements',
            name='right_ovary_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pelvicultrasoundmeasurements',
            name='ultrasound_image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.ultrasoundimage'),
        ),
        migrations.AlterField(
            model_name='pelvicultrasoundmeasurements',
            name='uterus_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pelvicultrasoundmeasurements',
            name='uterus_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pelvicultrasoundmeasurements',
            name='uterus_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='thyroidultrasoundmeasurements',
            name='isthmus_thickness',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='thyroidultrasoundmeasurements',
            name='left_lobe_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='thyroidultrasoundmeasurements',
            name='left_lobe_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='thyroidultrasoundmeasurements',
            name='left_lobe_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='thyroidultrasoundmeasurements',
            name='nodule_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='thyroidultrasoundmeasurements',
            name='nodule_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='thyroidultrasoundmeasurements',
            name='nodule_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='thyroidultrasoundmeasurements',
            name='right_lobe_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='thyroidultrasoundmeasurements',
            name='right_lobe_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='thyroidultrasoundmeasurements',
            name='right_lobe_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='thyroidultrasoundmeasurements',
            name='ultrasound_image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.ultrasoundimage'),
        ),
    ]
