# Generated by Django 5.1.5 on 2025-06-01 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_alter_abdominalultrasoundmeasurements_gallbladder_length_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abdominalultrasoundmeasurements',
            options={},
        ),
        migrations.AlterModelOptions(
            name='breastultrasoundmeasurements',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pelvicultrasoundmeasurements',
            options={},
        ),
        migrations.AlterModelOptions(
            name='thyroidultrasoundmeasurements',
            options={},
        ),
        migrations.RemoveField(
            model_name='abdominalultrasoundmeasurements',
            name='gallbladder_length',
        ),
        migrations.RemoveField(
            model_name='abdominalultrasoundmeasurements',
            name='gallbladder_width',
        ),
        migrations.RemoveField(
            model_name='abdominalultrasoundmeasurements',
            name='left_kidney_height',
        ),
        migrations.RemoveField(
            model_name='abdominalultrasoundmeasurements',
            name='left_kidney_length',
        ),
        migrations.RemoveField(
            model_name='abdominalultrasoundmeasurements',
            name='left_kidney_width',
        ),
        migrations.RemoveField(
            model_name='abdominalultrasoundmeasurements',
            name='liver_height',
        ),
        migrations.RemoveField(
            model_name='abdominalultrasoundmeasurements',
            name='liver_length',
        ),
        migrations.RemoveField(
            model_name='abdominalultrasoundmeasurements',
            name='liver_width',
        ),
        migrations.RemoveField(
            model_name='abdominalultrasoundmeasurements',
            name='right_kidney_height',
        ),
        migrations.RemoveField(
            model_name='abdominalultrasoundmeasurements',
            name='right_kidney_length',
        ),
        migrations.RemoveField(
            model_name='abdominalultrasoundmeasurements',
            name='right_kidney_width',
        ),
        migrations.RemoveField(
            model_name='abdominalultrasoundmeasurements',
            name='spleen_length',
        ),
        migrations.RemoveField(
            model_name='abdominalultrasoundmeasurements',
            name='spleen_width',
        ),
        migrations.RemoveField(
            model_name='breastultrasoundmeasurements',
            name='breast_side',
        ),
        migrations.RemoveField(
            model_name='breastultrasoundmeasurements',
            name='mass_height',
        ),
        migrations.RemoveField(
            model_name='breastultrasoundmeasurements',
            name='mass_length',
        ),
        migrations.RemoveField(
            model_name='breastultrasoundmeasurements',
            name='mass_width',
        ),
        migrations.RemoveField(
            model_name='pelvicultrasoundmeasurements',
            name='left_ovary_height',
        ),
        migrations.RemoveField(
            model_name='pelvicultrasoundmeasurements',
            name='left_ovary_length',
        ),
        migrations.RemoveField(
            model_name='pelvicultrasoundmeasurements',
            name='left_ovary_width',
        ),
        migrations.RemoveField(
            model_name='pelvicultrasoundmeasurements',
            name='right_ovary_height',
        ),
        migrations.RemoveField(
            model_name='pelvicultrasoundmeasurements',
            name='right_ovary_length',
        ),
        migrations.RemoveField(
            model_name='pelvicultrasoundmeasurements',
            name='right_ovary_width',
        ),
        migrations.RemoveField(
            model_name='pelvicultrasoundmeasurements',
            name='uterus_height',
        ),
        migrations.RemoveField(
            model_name='thyroidultrasoundmeasurements',
            name='isthmus_thickness',
        ),
        migrations.RemoveField(
            model_name='thyroidultrasoundmeasurements',
            name='left_lobe_height',
        ),
        migrations.RemoveField(
            model_name='thyroidultrasoundmeasurements',
            name='left_lobe_length',
        ),
        migrations.RemoveField(
            model_name='thyroidultrasoundmeasurements',
            name='left_lobe_width',
        ),
        migrations.RemoveField(
            model_name='thyroidultrasoundmeasurements',
            name='nodule_height',
        ),
        migrations.RemoveField(
            model_name='thyroidultrasoundmeasurements',
            name='nodule_length',
        ),
        migrations.RemoveField(
            model_name='thyroidultrasoundmeasurements',
            name='nodule_width',
        ),
        migrations.RemoveField(
            model_name='thyroidultrasoundmeasurements',
            name='right_lobe_height',
        ),
        migrations.RemoveField(
            model_name='thyroidultrasoundmeasurements',
            name='right_lobe_length',
        ),
        migrations.RemoveField(
            model_name='thyroidultrasoundmeasurements',
            name='right_lobe_width',
        ),
        migrations.AddField(
            model_name='abdominalultrasoundmeasurements',
            name='kidney_left_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='abdominalultrasoundmeasurements',
            name='kidney_right_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='abdominalultrasoundmeasurements',
            name='liver_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='abdominalultrasoundmeasurements',
            name='spleen_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='breastultrasoundmeasurements',
            name='mass_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='thyroidultrasoundmeasurements',
            name='left_lobe_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='thyroidultrasoundmeasurements',
            name='nodule_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='mm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='thyroidultrasoundmeasurements',
            name='right_lobe_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='cm', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='abdominalultrasoundmeasurements',
            name='ultrasound_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.ultrasoundimage'),
        ),
        migrations.AlterField(
            model_name='breastultrasoundmeasurements',
            name='distance_from_nipple',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='cm', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='breastultrasoundmeasurements',
            name='ultrasound_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.ultrasoundimage'),
        ),
        migrations.AlterField(
            model_name='pelvicultrasoundmeasurements',
            name='endometrial_thickness',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='mm', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pelvicultrasoundmeasurements',
            name='ultrasound_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.ultrasoundimage'),
        ),
        migrations.AlterField(
            model_name='pelvicultrasoundmeasurements',
            name='uterus_length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='cm', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pelvicultrasoundmeasurements',
            name='uterus_width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='cm', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='thyroidultrasoundmeasurements',
            name='ultrasound_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.ultrasoundimage'),
        ),
    ]
