# Generated by Django 5.1.5 on 2025-06-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_alter_abdominalultrasoundmeasurements_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultrasoundimage',
            name='annotated_image',
            field=models.ImageField(blank=True, null=True, upload_to='annotated_images/'),
        ),
    ]
