# Generated by Django 5.1.5 on 2025-06-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultrasoundexam',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='ultrasoundexam',
            name='clinical_diagnosis',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ultrasoundexam',
            name='findings',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ultrasoundexam',
            name='impression',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ultrasoundexam',
            name='medical_history',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ultrasoundexam',
            name='radiologist',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ultrasoundexam',
            name='recommendations',
            field=models.CharField(choices=[('FI', 'Further imaging'), ('FU', 'Follow-up ultrasound'), ('RS', 'Referral to specialist'), ('BI', 'Biopsy/FNA advised'), ('NF', 'No further workup needed')], default='NF', max_length=2),
        ),
        migrations.AlterField(
            model_name='ultrasoundexam',
            name='technologist',
            field=models.CharField(default='', max_length=100),
        ),
    ]
