# Generated by Django 5.2 on 2025-06-09 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0018_ultrasoundexam_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='emergency_contact_number',
        ),
    ]
