# Generated by Django 5.2 on 2025-06-09 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_remove_patient_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ultrasoundexam',
            name='annotations',
        ),
        migrations.RemoveField(
            model_name='ultrasoundexam',
            name='clinical_diagnosis',
        ),
        migrations.RemoveField(
            model_name='ultrasoundexam',
            name='doppler_site',
        ),
        migrations.RemoveField(
            model_name='ultrasoundexam',
            name='medical_history',
        ),
        migrations.RemoveField(
            model_name='ultrasoundexam',
            name='other_procedure',
        ),
        migrations.RemoveField(
            model_name='ultrasoundexam',
            name='radiologist',
        ),
        migrations.RemoveField(
            model_name='ultrasoundexam',
            name='radiologist_signature',
        ),
        migrations.RemoveField(
            model_name='ultrasoundexam',
            name='technologist',
        ),
        migrations.RemoveField(
            model_name='ultrasoundexam',
            name='technologist_notes',
        ),
        migrations.RemoveField(
            model_name='ultrasoundexam',
            name='technologist_signature',
        ),
    ]
