# Generated by Django 5.2 on 2025-06-09 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0020_remove_ultrasoundexam_annotations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ultrasoundexam',
            name='amniotic_fluid',
        ),
        migrations.RemoveField(
            model_name='ultrasoundexam',
            name='edd',
        ),
        migrations.RemoveField(
            model_name='ultrasoundexam',
            name='efw',
        ),
        migrations.RemoveField(
            model_name='ultrasoundexam',
            name='fetal_heart_rate',
        ),
        migrations.RemoveField(
            model_name='ultrasoundexam',
            name='fetal_sex',
        ),
        migrations.RemoveField(
            model_name='ultrasoundexam',
            name='or_number',
        ),
        migrations.RemoveField(
            model_name='ultrasoundexam',
            name='placenta_grade',
        ),
        migrations.RemoveField(
            model_name='ultrasoundexam',
            name='placenta_location',
        ),
    ]
