# Generated by Django 5.2 on 2025-08-05 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0021_remove_ultrasoundexam_amniotic_fluid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_type', models.CharField(choices=[('ABD', 'Abdominal Ultrasound'), ('PEL', 'Pelvic Ultrasound'), ('OBS', 'Obstetric Ultrasound'), ('TVS', 'Transvaginal Ultrasound'), ('BRE', 'Breast Ultrasound'), ('THY', 'Thyroid Ultrasound'), ('SCR', 'Scrotal Ultrasound'), ('DOP', 'Doppler Ultrasound'), ('OTH', 'Other')], max_length=3)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('reason', models.TextField(help_text='Reason for appointment or symptoms')),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
            ],
            options={
                'ordering': ['-appointment_date', '-appointment_time'],
            },
        ),
    ]
