# Generated by Django 5.1.5 on 2025-08-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0022_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.AddField(
            model_name='patient',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
