# Generated by Django 5.1.5 on 2025-08-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0023_remove_patient_age_patient_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
