# Generated by Django 5.1.5 on 2025-09-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0024_patient_archived_at_patient_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultrasoundexam',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the examination', null=True),
        ),
        migrations.AddField(
            model_name='ultrasoundexam',
            name='technician',
            field=models.CharField(blank=True, help_text='Technician who performed the exam', max_length=100, null=True),
        ),
    ]
