# Generated by Django 5.1.5 on 2025-11-12 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0026_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('APPOINTMENT_BOOKED', 'New Appointment Booked'), ('APPOINTMENT_CONFIRMED', 'Appointment Confirmed'), ('APPOINTMENT_CANCELLED', 'Appointment Cancelled'), ('APPOINTMENT_UPDATED', 'Appointment Updated'), ('EXAM_CREATED', 'New Exam Created'), ('EXAM_UPDATED', 'Exam Updated'), ('EXAM_COMPLETED', 'Exam Completed'), ('GENERAL', 'General Notification')], max_length=25),
        ),
    ]
