# Generated by Django 5.1.5 on 2025-12-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0028_patient_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breastultrasoundmeasurements',
            name='ultrasound_image',
        ),
        migrations.RemoveField(
            model_name='pelvicultrasoundmeasurements',
            name='ultrasound_image',
        ),
        migrations.RemoveField(
            model_name='thyroidultrasoundmeasurements',
            name='ultrasound_image',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='procedure_type',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='AbdominalUltrasoundMeasurements',
        ),
        migrations.DeleteModel(
            name='BreastUltrasoundMeasurements',
        ),
        migrations.DeleteModel(
            name='PelvicUltrasoundMeasurements',
        ),
        migrations.DeleteModel(
            name='ThyroidUltrasoundMeasurements',
        ),
    ]
