# Generated by Django 5.1.5 on 2025-12-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0030_patient_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='completed_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
