# Generated by Django 5.1.5 on 2025-12-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0031_appointment_completed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
