# Generated by Django 5.1.5 on 2025-12-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0032_alter_appointment_completed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='referral_image',
            field=models.ImageField(blank=True, help_text='Upload referral paper/document', null=True, upload_to='referrals/%Y/%m/%d/'),
        ),
    ]
