# Generated by Django 5.1.5 on 2026-01-05 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0033_appointment_referral_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateTimeField(verbose_name='Admission Date & Time')),
                ('expected_discharge_date', models.DateTimeField(verbose_name='Expected Discharge Date & Time')),
                ('actual_discharge_date', models.DateTimeField(blank=True, null=True, verbose_name='Actual Discharge Date & Time')),
                ('room_number', models.CharField(max_length=20, verbose_name='Room Number')),
                ('admission_reason', models.TextField(verbose_name='Reason for Admission')),
                ('attending_physician', models.CharField(max_length=100, verbose_name='Attending Physician')),
                ('discharge_notes', models.TextField(blank=True, null=True, verbose_name='Discharge Notes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Admission',
                'verbose_name_plural': 'Admissions',
                'ordering': ['-admission_date'],
            },
        ),
    ]
