# Generated by Django 5.1.5 on 2026-01-15 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0034_admission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ultrasoundexam',
            name='performed_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who performed this examination', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_exams', to=settings.AUTH_USER_MODEL, verbose_name='Performed By'),
        ),
    ]
